source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-assets'
gem 'maruku'
gem 'sass'
gem 'uglifier'
gem 'github-pages'
gem 'ruby-oembed', '~> 0.8.10'
gem 'jekyll-lunr-js-search'
gem 'rake', '~> 0.8.7'